[package]
name = "chengine"
version = "0.1.0"
authors = ["machengim <machengiam@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
comrak = "0.6.2"
chrono = "0.4.9"
postgres = "0.16.0-rc.2"